name: Run project on push to main or at 1 AM every Monday

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 1 * * 1" # 每周一凌晨1点执行

jobs:
  build:
    runs-on: ubuntu-latest
    env: # 设置作业级别的环境变量
      POSTGRES_PRISMA_URL: ${{ secrets.POSTGRES_PRISMA_URL }}
      POSTGRES_URL_NON_POOLING: ${{ secrets.POSTGRES_URL_NON_POOLING }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm ci

      - name: generate prisma client
        run: npx prisma generate

      - name: Run project
        run: npm run start
